apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-manager-k12-components
  namespace: "argocd"
spec: 
  destination:
    name: k12
    namespace: cert-manager
  project: default
  source:
    path: registry/clusters/k12/cert-issuers
    repoURL: https://github.com/k1-digitalocean/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
