# host name are hardcoded for now. Future overrride should
# be stored/referenced inside customers Gitops repo.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k1-digitalocean-zippy-k12
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: 555935582951.dkr.ecr.us-west-2.amazonaws.com/k1-digitalocean/charts/zippy
    chart: k1-digitalocean-zippy
    targetRevision: 0.1.0-rc.aab9696
    helm:
      values: |-
        k1-digitalocean-zippy:
          image:
            repository: 555935582951.dkr.ecr.us-west-2.amazonaws.com/k1-digitalocean/zippy
          ingress:
            className: nginx
            enabled: true
            annotations:
              nginx.ingress.kubernetes.io/service-upstream: "true"
              cert-manager.io/issuer: letsencrypt-prod
            hosts:
              - host: k1-digitalocean-zippy-k12.gitopsmagic.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: k1-digitalocean-zippy-tls
                hosts:
                  - k1-digitalocean-zippy-k12.gitopsmagic.com
  destination:
    name: k12
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
